### Register
POST https://my-twitter-clone.vercel.app/api/register/
Content-Type: application/json

{
  "username": "siddharth",
  "password": "45_siddharth",
  "name": "Siddharth",
  "gender": "male"
}

###

### Login
POST https://my-twitter-clone.vercel.app/api/login/
Content-Type: application/json

{
  "username": "siddharth",
  "password": "45_siddharth"
}

###

### Tweets Feed
GET https://my-twitter-clone.vercel.app/api/user/tweets/feed/
Authorization: Bearer <your-jwt-token>

###

### Following
GET https://my-twitter-clone.vercel.app/api/user/following/
Authorization: Bearer <your-jwt-token>

###

### Followers
GET https://my-twitter-clone.vercel.app/api/user/followers/
Authorization: Bearer <your-jwt-token>

###

### Tweet Details
GET https://my-twitter-clone.vercel.app/api/tweets/1/
Authorization: Bearer <your-jwt-token>

###

### Tweet Likes
GET https://my-twitter-clone.vercel.app/api/tweets/1/likes/
Authorization: Bearer <your-jwt-token>

###

### Tweet Replies
GET https://my-twitter-clone.vercel.app/api/tweets/1/replies/
Authorization: Bearer <your-jwt-token>

###

### My Tweets
GET https://my-twitter-clone.vercel.app/api/user/tweets/
Authorization: Bearer <your-jwt-token>

###

### Post Tweet
POST https://my-twitter-clone.vercel.app/api/user/tweets/
Authorization: Bearer <your-jwt-token>
Content-Type: application/json

{
   "tweet": "Hi Hello!!"
}

###

### Delete Tweet
DELETE https://my-twitter-clone.vercel.app/api/tweets/4/
Authorization: Bearer <your-jwt-token>
